name: Cypress tests for stopwatch
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # first, install dependencies and Cypress
      # from the root folder using the lock file
      - name: Cypress install
        uses: cypress-io/github-action@v2.9.7
        with:
         start: npm start
         runTests: true
         
      - name: Record tests
        with:
          record: true
          env: CYPRESS_RECORD_KEY:{8ef3a184-0c12-4f21-9925-2841a226310a}
