name: subfolder
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # first, install dependencies and Cypress
      # from the root folder using the lock file
      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: true
